# 图与图寻系统配置文件
# Pic Search System Configuration

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8000
  debug: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:3001"

# 数据库配置
database:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "1234"
  database: "pic_search"
  charset: "utf8mb4"
  pool_size: 10
  pool_recycle: 3600

# 文件存储配置
storage:
  upload_dir: "D:\\codes\\Projects\\pic-search\\faiss-image-search-v3\\backend\\data\\images"
  max_file_size: 10485760  # 10MB
  allowed_extensions:
    - "jpg"
    - "jpeg"
    - "png"
    - "bmp"
    - "webp"
  thumbnail_size: [256, 256]

# Faiss索引配置
faiss:
  index_path: "D:\\codes\\Projects\\pic-search\\faiss-image-search-v3\\backend\\data\\index\\image_features.index"
  feature_dim: 2048
  index_type: "IndexFlatIP"  # 内积相似度索引
  nprobe: 10

# 深度学习模型配置
model:
  name: "resnet50"
  pretrained: true
  device: "cpu"  # 默认使用CPU，有GPU可改为cuda
  batch_size: 32

# 认证配置
auth:
  secret_key: "pic-search-secret-key-change-in-production-2024"
  algorithm: "HS256"
  access_token_expire_minutes: 1440  # 24小时

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# 搜索配置
search:
  default_k: 10
  max_k: 100
  similarity_threshold: 0.5

# 管理员配置
admin:
  default_username: "admin"
  default_password: "admin123" 